# =============================================================================
# config.py
# Single source of truth for all constraints, limits, and initial conditions.
# Swap values here when the real Honeywell simulator constraints are provided.
# =============================================================================

# ---------------------------------------------------------------------------
# Production Target
# ---------------------------------------------------------------------------
TARGET_FLOW_INITIAL = 100.0  # bbl/hr — default startup target

# ---------------------------------------------------------------------------
# Choke Constraints
# ---------------------------------------------------------------------------
CHOKE_MIN = 0.0       # % minimum choke opening
CHOKE_MAX = 100.0     # % maximum choke opening
CHOKE_MAX_STEP = 5.0  # % maximum movement per control interval (ramp rate limit)

# Discrete candidate moves evaluated by MPC at each step
CHOKE_CANDIDATES = [-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0]  # delta % added to current choke

# ---------------------------------------------------------------------------
# Active Pressure Constraints  (must never be violated)
# Values calibrated to CSV data: WHP ~216-270, FLP ~153-189, BHP ~2883-3137
# ---------------------------------------------------------------------------
WHP_MIN = 100.0    # psi  (absolute floor — well integrity)
WHP_MAX = 350.0    # psi  (upper safety limit)

FLP_MIN = 100.0    # psi
FLP_MAX = 250.0    # psi  (adjusted; CSV max ~189, adding headroom)

BHP_MIN = 2500.0   # psi
BHP_MAX = 3500.0   # psi

# ---------------------------------------------------------------------------
# Warning Buffer (for Inertia-Aware Safety Buffer in MPC)
# Triggers a pre-emptive pullback when within this % of a hard limit
# ---------------------------------------------------------------------------
CONSTRAINT_WARNING_BUFFER_PCT = 0.05  # 5% of full range

# ---------------------------------------------------------------------------
# Control Timing
# ---------------------------------------------------------------------------
CONTROL_INTERVAL = 1  # hours per MPC step
PREDICTION_HORIZON = 3  # steps ahead for receding horizon lookahead

# ---------------------------------------------------------------------------
# Simulator Initial State
# Matches row 0 of the CSV step-test dataset
# ---------------------------------------------------------------------------
INITIAL_STATE = {
    "choke":  30.0,    # %
    "Q":      90.0,    # bbl/hr
    "WHP":   250.0,    # psi
    "FLP":   180.0,    # psi
    "BHP":  3000.0,    # psi
}

# ---------------------------------------------------------------------------
# Surrogate Model
# ---------------------------------------------------------------------------
MODEL_PATH = "predictive_model.pkl"   # relative path; generated by system_identification.py
NOISE_STD = {
    "Q":   0.5,    # bbl/hr Gaussian noise added to simulator output
    "WHP": 0.3,    # psi
    "FLP": 0.2,    # psi
    "BHP": 2.0,    # psi
}

# ---------------------------------------------------------------------------
# Dashboard Scenario Definitions
# ---------------------------------------------------------------------------
SCENARIOS = {
    "A": {
        "name": "Scenario A — Startup to Target",
        "description": "Bring well from cold-start (Choke=30%, Q≈90 bbl/hr) to a specified production target.",
        "target_q": 130.0,
        "target_q_min": 80.0,
        "target_q_max": 160.0,
    },
    "B": {
        "name": "Scenario B — Target Tracking",
        "description": "Mid-run target step change. Controller tracks the new target while respecting all constraints.",
        "target_q_initial": 100.0,
        "target_q_step": 150.0,
        "step_at_hour": 15,
        "target_q_min": 80.0,
        "target_q_max": 160.0,
    },
    "C": {
        "name": "Scenario C — Infeasible Target",
        "description": "Requested target exceeds safe production limits. Controller activates Edge-Riding mode.",
        "target_q": 200.0,   # known infeasible — triggers edge-riding
        "target_q_min": 160.0,
        "target_q_max": 220.0,
    },
}

# ---------------------------------------------------------------------------
# Informational Variables (not active constraints per problem statement)
# Included for completeness and future extension
# ---------------------------------------------------------------------------
# WHT — Wellhead Temperature
# AP  — Annulus Pressure
